
kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: "/root/.influxdb"
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          livenessProbe:
            exec:
              command:
              - sh
              - health.sh
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock 
  selector:
    matchLabels:
      app: influxdb 